USE ace_shard;

ALTER TABLE `character_login`
MODIFY COLUMN `characterId` BIGINT UNSIGNED NOT NULL;

ALTER TABLE `pk_stats_kills`
MODIFY COLUMN `killer_id` BIGINT UNSIGNED NOT NULL,
MODIFY COLUMN `victim_id` BIGINT UNSIGNED NOT NULL;

ALTER TABLE `pk_stats_damage`
MODIFY COLUMN `attacker_id` BIGINT UNSIGNED NOT NULL,
MODIFY COLUMN `defender_id` BIGINT UNSIGNED NOT NULL;

ALTER TABLE `pk_trophy_cooldown`
MODIFY COLUMN `killer_id` BIGINT UNSIGNED NOT NULL,
MODIFY COLUMN `victim_id` BIGINT UNSIGNED NOT NULL;
