name: 'Pourtide Release'

on:
  push:
    branches:
      - master
      - test  

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t apourman/pourtide:latest .

      - name: Push Docker image to Docker Hub
        run: docker push apourman/pourtide:latest

      - name: Run bash script on remote machine with sudo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.REMOTE_PASSPHRASE }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /ace/Docker
            sudo ./pull-from-dockerhub.sh
